In [9]:
# Printing numbers from 0-100 using while keyword
a=0
while a<=100 :
    print(a)
    a= a+1

0

In [1]:
# Printing numbers from 0-100 using break keyword
a=0
while True:
    print(a+1)
    a=a+1
    if a==100:
        break

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [4]:
a=0
while True:
    if a==100:
        break
    else:
        print (a+1)
        a=a+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [12]:
#Using while loop for even numbers btw 0-100
a=0
while a<=100:
    if a%2==0:
        print(a)
    a=a+1

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

In [10]:
#Using while loop for odd num btw 0-100
a=0
while a<=100:
    a=a+1
    if a%2==0:
        continue
    print(a)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99
101

In [2]:
#Using while loop for a login datababse
Login_username= 'Michael'
Login_password= 'Ayomie'

Database_username= 'Michael'
Database_password= 'Ayomide'
count=0
while True:
    if Login_username== Database_username and Login_password== Database_password :
        print ('Login successful')
        break
    elif count>=3:    
        print ('account disabled')
        break
    else :
        print ('try again')
    count+=1

try again
try again
try again
account disabled

In [7]:
#Using for loop to print num from 0-10
for i in range(11):
    print(i)

0
1
2
3
4
5
6
7
8
9
10

In [8]:
#Using for loop to print num from 0-100
for j in range(101):
    print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [12]:
#Using for loop to print even numbers from 0-100
a=0
for a in range(101):
    a<=101
    if a%2==0:
        print(a)
    a=a+1

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

In [15]:
for j in range(5,101):
    print(j)

5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

In [17]:
#using for loop even num btw 0-100 using range(start,stop,interval)
for j in range(0,101,2):
    print(j)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

In [18]:
for j in range(1,100,2):
    print(j)

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79
81
83
85
87
89
91
93
95
97
99

In [21]:
integer=['my','name','is','Ayo']
for i in integer:
    print(i)

my
name
is
Ayo

In [41]:
for j in reversed(range(11)):
    print(j)

10
9
8
7
6
5
4
3
2
1
0